version: '3'
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
      - '5000:5000'
    links:
      - ups-plugin
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: ups-plugin:5001

  ups-plugin:
    container_name: ups-plugin
    image: vaporio/snmp-ups-plugin
    expose:
      - '5001'
    ports:
      - '6060:6060'
    volumes:
      - './config.yml:/etc/synse/plugin/config/config.yml'
    links:
      - snmp-emulator

  snmp-emulator:
    container_name: snmp-emulator
    image: vaporio/snmp-emulator
    expose:
      - '1024/udp'
    command:
      - '--data-dir=mibs/ups'
      - '--agent-udpv4-endpoint=0.0.0.0:1024'
      - '--v3-user=simulator'
      - '--v3-auth-key=auctoritas'
      - '--v3-auth-proto=SHA'
      - '--v3-priv-key=privatus'
      - '--v3-priv-proto=AES'